add: implement ox menus, remove armoury
Qbox-project/qb-policejob pull request #7
Opened 2022-11-26 21:42 UTC by JoeSzymkowiczFiveM

**Describe Pull request**
Converted several instances of qb-input and qb-menu to ox_lib elements. Started unifying non-target interaction elements to textUI. Removed police armory, as this is handled within ox_inventory.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-11-26 23:13 UTC, JoeSzymkowiczFiveM commented
Closing to prevent conflicting PRs with #8

2022-12-08 06:54 UTC, BerkieBb requested changes

2022-12-08 06:54 UTC, BerkieBb commented on client/job.lua
> +            onEnter = function(_)
This underscore is useless

2022-12-08 06:54 UTC, BerkieBb commented on client/job.lua
> +                        lib.showTextUI('[E] - Police Impound')
Add a language entry for this one as well

2022-12-08 06:55 UTC, BerkieBb requested changes

2022-12-08 06:55 UTC, BerkieBb commented on client/objects.lua
> +			Wait(3)
Why this random 3?

2022-12-08 17:13 UTC, JoeSzymkowiczFiveM commented on client/objects.lua
> +			Wait(3)
`3` was the original value set to the sleep when user is logged in and in a vehicle; `spikeSleep = 3`. When user was not both, it was `spikeSleep = 1000`. Since this event can only fire now when user is logged in and in a vehicle, no reason to set this to a variable.

2022-12-08 17:16 UTC, JoeSzymkowiczFiveM commented on client/job.lua
> +                        lib.showTextUI('[E] - Police Impound')
Reference to locale fixed.

2022-12-08 17:47 UTC, BerkieBb commented on client/objects.lua
> +			Wait(3)
Change it to either 0 or something from 100 or above, because 3 is meaningless, it can even cause problems if you need it to run every frame

2022-12-08 19:26 UTC, JoeSzymkowiczFiveM commented on client/objects.lua
> +			Wait(3)
Increased to 100, tested change with vehicles traveling various speeds.

2022-12-08 20:01 UTC, BerkieBb approved these changes

2022-12-08 22:52 UTC, merged