Overall update
Qbox-project/qb-policejob pull request #8
Opened 2022-11-26 22:47 UTC by userMacieG

ox support
code cleanup + reformatted

This is not a final version.

2022-11-30 20:13 UTC, JoeSzymkowiczFiveM reviewed
The code is functionally working, and just about all of my comments are around formatting, and did not touch on EVERY instance I disagreed with. If someone wants to overrule me, I would be happy to have that conversation, but I would prefer the formatting changes be reverted before merge.

2022-11-30 20:13 UTC, JoeSzymkowiczFiveM commented on server/main.lua
> +QBCore.Commands.Add("pobject", Lang:t("commands.place_object"), {
Seems like a per-line character limit is being used, to determine line breaks is that right? I don't like that certain functions' arguments are broken and some are not. Other reviewers thoughts on this are welcomed.

2022-11-30 20:13 UTC, JoeSzymkowiczFiveM commented on server/main.lua
> +    local src = source
Making source into a new variable is not needed here.

2022-11-30 20:13 UTC, JoeSzymkowiczFiveM commented on server/main.lua
> +        2
I don't like leaving the argument floating out on a line by itself in this case.

2022-11-30 20:13 UTC, JoeSzymkowiczFiveM commented on server/main.lua
> +            MySQL.query('UPDATE player_vehicles SET state = ?, body = ?, engine = ?, fuel = ? WHERE plate = ?', {
This seems like a waste of vertical space.

2022-11-30 20:48 UTC, YvanCywan commented on server/main.lua
> +QBCore.Commands.Add("pobject", Lang:t("commands.place_object"), {
There's also a block of code underneath, hence why I put it all on one line to begin with, to highlight the executed code underneath.

2022-11-30 21:16 UTC, BerkieBb requested changes

2022-11-30 21:16 UTC, BerkieBb commented on client/job.lua
> +            onEnter = function(_)
Useless underscore

2022-11-30 21:16 UTC, BerkieBb commented on client/objects.lua
> +    end
Why 2 seperate if statements to do the same?

2022-11-30 21:16 UTC, BerkieBb commented on client/tracker.lua
> +            ["accessory"] = {
If you are going to remove [""] from the variable calls, you can remove them from the creation part

2022-11-30 21:16 UTC, BerkieBb commented on server/main.lua
> +    local src = source
Not necessary at all, this event does not yield anywhere

2022-11-30 21:17 UTC, BerkieBb commented
Whilst you're at it, move the inline css from the html to the css file, that'd clean up a lot

2022-11-30 21:18 UTC, BerkieBb commented
For my reviews, I didn't do all cases, rather just one per 'situation'

2022-11-30 21:22 UTC, YvanCywan requested changes

2022-11-30 21:22 UTC, YvanCywan commented on config.lua
> +    }
Just why?

Nothing on those lines really needs to be changed so much that it warrants expanding it out more.

Also joaat isn't necessarily the best thing to apply here, the prop name itself is all that is needed

2022-11-30 21:22 UTC, YvanCywan commented on config.lua
> -    ["duty"] = {
These are necessary considering the way some of the code is written. Not sure why they have been changed.

2022-11-30 21:22 UTC, YvanCywan commented on server/main.lua
> +
this should return to how it was before

2022-11-30 21:22 UTC, YvanCywan commented on server/main.lua
> +        })
same with this, and everything similar for that matter.

2022-11-30 21:22 UTC, YvanCywan commented on server/main.lua
> +    end
One liners that should be returned back to the way they were.

2022-11-30 21:22 UTC, YvanCywan commented on server/main.lua
> +    local src = source
In all the other functions, this was removed by him, and now this is being added.

2022-11-30 21:22 UTC, YvanCywan commented on server/main.lua
> +    end
```suggestion
	if args[1] then message = table.concat(args, " ") end
```

2022-11-30 21:26 UTC, YvanCywan commented
These are the things that bother me for the moment, while this is functional, I don't believe that the majority of changes here are necessary.

2022-11-30 21:33 UTC, BerkieBb commented on server/main.lua
> +QBCore.Commands.Add("pobject", Lang:t("commands.place_object"), {
Rather have it on the same line

2022-11-30 21:33 UTC, BerkieBb commented on server/main.lua
> +    local src = source
So you can remove it now, you only assign it to a variable if the event is yielding (a wait for example)

2022-12-04 17:57 UTC, Manason commented
Needs to be split into smaller PRs.

2022-12-04 21:15 UTC, closed without merging